version: "3.7"
services:
  db:
    image: postgres:11
    restart: unless-stopped
    env_file:
      - db_service_settings.env
    volumes:
      - app_pg_data:/var/lib/postgresql/data # directory where actual postgres data is stored

  boxex_listener:
    image: senyehor/server:latest
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: unless-stopped



#    healthcheck: pg vibe
  #      test: [ "CMD", "pg_isready", "-U", "$POSTGRES_USER" ]
  #      timeout: 45s
  #      interval: 10s
  #      retries: 10