version: "3.7"
services:
  db:
    container_name: db
    image: postgres:11
    volumes:
      - "db_data:/var/lib/postgresql/data"
    restart: unless-stopped

  box_listener:
    container_name: box_listener
    image: senyehor/box_listener:latest
    depends_on:
      - db
    ports:
      - "9000:9000"
    env_file:
      - dev_config.env
      - packet_config.env
    restart: unless-stopped

  #  nginx:
  #    container_name: nginx
  #    build:
  #      context: ./
  #      dockerfile: nginx.dockerfile
  #    ports:
  #      - "8000:8000"
  #    restart: unless-stopped

volumes:
  db_data: